services:
- type: web
  name: speedscan
  env: python
  region: oregon
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn -b :$PORT app:app"
  envVars:
    - key: ENV_VAR_NAME
      value: "env_var_value"
  autoDeploy: true
  plan: starter-plus
  scale:
    cpu: 2
    memoryGB: 2
    instances:
      min: 1
      max: 10
